publishing_topics:
  wheel_velocities: "/wheel_velocity_controller/command"
subscribing_topics:
  pose: "/gazebo/model_states"
  path: "/Path"
meta_parameters:
  log: True
  visualize: True
robot_parameters:
  width: 0.8
  maxVelocity: 1.57
algorithm_parameters:
  KL: 0.25
  KC: 0.05
  localPath: True