iPose:
  position: {x: 18.6474, y: 10.8159, z: 0.0}
  orientation: {x: -1.0, y: 0.0, z: 0.0, w: 0.0}
  IMUorientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
  CAMERAwrtGPS: {x: 0.0, y: 0.0, z: 0.0}

UKF:
  alpha: 3.0
  beta: 2.0
  kappa: 0.1
  n_state_dim: 9
  g0: {x: 0, y: 0, z: 1}
  B_INTENSITY: 0.0000440257
  INCLINATION: 0.79649845744
  DECLINATION: 0.07891855279
  Q: 0.01
  R: 0.7
  R_gps: 100.0
  RLL: 1.0
  LLMax: 0.3
  P_q0: 0.5
  P_q1: 0.5
  P_q2: 0.5
  P_q3: 0.5
  P_omega_x: 0.5
  P_omega_y: 0.5
  P_omega_z: 0.5
  P_x: 0.5
  P_y: 0.5

  GPS_State: false
  IMU_State: true
  BNO_State: false
  ENCODER_State: true
  Landmark_State: true