APF_update:
  # force coefficients
  KATT: 8               # Attractive gain
  KREP: 100              # Repulsive gain
  KENHANCED: 80          # Enhanced attraction gain
  KGRADIENT: 0.1         # Costmap gradient coefficient

  # Obstacle parameters
  QSTAR: 1             # Influence range threshold (meters)
  obstacle_topic: "obstacleArrayTopic"  # Topic name for obstacles

  # Path following parameters
  M: 1                   # Potential field exponent
  LOOKAHEADDIST: 1.2      # Lookahead distance (meters)
  CHECKPOINTDIST: 1.2    # Checkpoint triggering distance (meters)


  # Time parameters
  TAU: 0.1               # Time step for simulation (seconds)