APF_update:
  # force coefficients
  KATT: 8               # Attractive gain
  KREP: 100              # Repulsive gain
  KENHANCED: 80          # Enhanced attraction gain
  KGRADIENT: 0.1         # Costmap gradient coefficient
 

  # Obstacle parameters
  QSTAR: 0.8             # Influence range threshold (meters)
  obstacle_topic: "obstacleArrayTopic"  # Topic name for obstacles
  OBSTACLE_CHECKPOINT_DIST: 0.5  # Distance to ignore checkpoints near obstacles (meters)

  # Path following parameters
  M: 1                   # Potential field exponent
  CHECKPOINTDIST: 1.2    # Checkpoint triggering distance (meters)
  LOOKAHEAD_STEPS: 9    # Number of lookahead steps for path following

  # Path file parameters
  pathFile: "~/ERC25-Xavier-WS/src/ROAR-Autonomous-System/Path_Planning/heightmap_costmap/Results/straight_line_path.csv"
  costmapFile: "~/ERC25-Xavier-WS/src/ROAR-Autonomous-System/Path_Planning/heightmap_costmap/Results/total_cost.csv"


  # Time parameters
  TAU: 0.1               # Time step for simulation (seconds)

  # Pixel scale
  PIXEL_SCALE: 20
  GRADIENT_RADIUS: 1
